version: '3.1'
services:
 db:
   image: postgres:13
   container_name: instatic_db
   environment:
     - POSTGRES_DB=instatic
     - POSTGRES_PASSWORD=admin
     - POSTGRES_USER=admin
   ports:
     - "5434:5432"
   volumes:
     - local_pgdata:/var/lib/postgresql/data
 pgadmin:
   image: dpage/pgadmin4
   container_name: pg_UF3
   ports:
     - "80:80"
   environment:
     PGADMIN_DEFAULT_EMAIL: pol@gmail.com
     PGADMIN_DEFAULT_PASSWORD: pol123
   volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
 local_pgdata:
 pgadmin-data: